### ISSUE TITLE
icon选择器会影响到全局

### ISSUE THREAD

**Issue by UltimeLam** [top-dante/wangeditor-antd#8]
![image](https://user-images.githubusercontent.com/35449771/149325336-5a50248c-e943-4a84-a4e1-49bc3c187531.png)
![image](https://user-images.githubusercontent.com/35449771/149325377-50a1d2b2-0ac6-43d1-893d-5898e3447a54.png)

**Comment by UltimeLam** [comment]
![image](https://user-images.githubusercontent.com/35449771/149325592-63490f0a-e3b3-44d4-b77d-8baca406747d.png)

**Comment by top-dante** [comment]
收到 我修复一下

**Comment by top-dante** [comment]
已修复请更新到1.0.8
